### ISSUE TITLE
"Download failed" after upgrade to onlyoffice - unable to verify the first certificate

### ISSUE THREAD

**Issue by thomass4t** [ONLYOFFICE/Docker-DocumentServer#96]
I upgraded to the current community- and document-server 9.6.1.627
Community-Server runs with self-signed SSL certificate
Document-Server runs with plain http

After restart of the two docker containers, I get an error message when opening any kind of document. The error message merely shows "Download failed".

I discovered the underlying error within the logfile
/app/onlyoffice/DocumentServer/logs/documentserver/converter/out.log

Whenever I open a document, an error shows up in this logfile:

[2018-04-10 14:17:05.216] [ERROR] nodeJS - error downloadFile:url=https://onlyoffice/products/files/httphandlers/filehandler.ashx?action=stream&fileid=4&version=6&stream_auth=xxx;attempt=3;code:UNABLE_TO_VERIFY_LEAF_SIGNATURE;connect:undefined;(id=PryKqIixHZSmYe_LEsQ_)
**Error: unable to verify the first certificate**
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:609:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:439:38)

The document-Server seems to download something from the community-server and fails because it doesn't know the CA of the self-signed certificate.

How can I add my self-signed certificate or my CA to the document-server?
My CA must be injected to Node-JS service.
(Adding it to /etc/ssl/certs didn't work and also setting the docker-env NODE_TLS_REJECT_UNAUTHORIZED=0 didn't help either)

Thanks for any suggestions,
Thomas

**Comment by dmkash** [comment]
I am running into the same problem while setting up local virtual machines in our development environment.  For our development virtual machines we use the .test TLD, so need to use self-signed certificates. 

The ONLYOFFICE Document Server has been installed on a CentOS 7 virtual machine following the directions here:  https://helpcenter.onlyoffice.com/server/linux/document/linux-installation-centos.aspx

I tried adding `NODE_TLS_REJECT_UNAUTHORIZED=0` to the /etc/onlyoffice/documentserver/supervisor/onlyoffice-documentserver-docservice.ini but this didn't work, either. I'm seeing the exact same error in /var/log/onlyoffice/documentserver/docservice/out.log as the OP:

```
[2018-07-13 14:50:22.799] [ERROR] nodeJS - postData error: docId = 2_2_;url = https://testserver.ourdomain.test/path/to/document;data = {"key":"2_2_","status":1,"users":["1"],"actions":[{"type":1,"userid":1}]}
Error: self signed certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)
```

**Comment by agolybev** [comment]
Hi Dana, try turning off validating certificate by Document Server. Set `services.CoAuthoring.requestDefaults.rejectUnauthorized=false` in `/etc/onlyoffice/documentserver/defaults.json` file and restart documentserver serviceis with `supervisorctl restart all`.

**Comment by inpos** [comment]
Unfortunately, node.js don't use system ca-certs and this issue can't be fixed by adding local CA cert to system bundle. Workaround by @agolybev work, but breaks SSL security due to grant connections to unauthorized ssl servers.

**Comment by thomaswollburg** [comment]
The workaround does work, but pretty pretty please update your documentation as I have tried all -e SSL_VERIFY_CLIENT="off" -e NODE_TLS_REJECT_UNAUTHORIZED=0 and what not to make this work. Can I invoice these useless hours of frustration somewhere? Even set up chain file and gave it the recommend name and everything. Nothing helped here.

**Comment by ibnpetr** [comment]
@thomaswollburg 
Next version of the DocumentServer container will include node.js v8, it does use system CA bundle, you will be able to import your certificates without having to disable verification.

**Comment by changchichung** [comment]
@ibnpetr is there any schedule for next release ?

**Comment by skuep** [comment]
@ibnpetr 
I am curious, are you already using node v8? When I execute the following in the onlyoffice docker container, I get:

`docker exec <id> node -v`
`v8.14.0`

However I am having the exact same issues as above. Also tried every workaround given above.

**Comment by mrwormo** [comment]
Hi,
I'm using the latest docker image with Traefik as reverse proxy, and i have the same problem.

The trick to turning off validating certificate by Document Server works great :
> Set `services.CoAuthoring.requestDefaults.rejectUnauthorized=false` in `/etc/onlyoffice/documentserver/defaults.json` file and restart documentserver serviceis with `supervisorctl restart all`.

But how can i modify the default.json at start of the container ? `services.CoAuthoring.requestDefaults.rejectUnauthorized` seems to not be modified by an environment variable (https://github.com/ONLYOFFICE/Docker-DocumentServer#available-configuration-parameters).

**Comment by mrwormo** [comment]
Hi @ShockwaveNN,
This command works just fine. Many thx !
Now i need to run the command when the container starts. I tried to put this line at the end of the Docker-compose.yml, but it doesn't work.
I continue to search a solution to automate this...

**Comment by ShockwaveNN** [comment]
@mrwormo I think there is no elegant way to use this command witho Docker Compose, you can modify https://github.com/ONLYOFFICE/Docker-DocumentServer/blob/master/run-document-server.sh to add this command and rebuild image locally

**Comment by mrwormo** [comment]
@ShockwaveNN I actually thought about modifying [https://github.com/ONLYOFFICE/Docker-DocumentServer/blob/master/run-document-server.sh](https://github.com/ONLYOFFICE/Docker-DocumentServer/blob/master/run-document-server.sh), and build my own image, but that means that we would have to rebuild the image each time we update.

**Comment by ShockwaveNN** [comment]
@mrwormo I think you can try to move running `run-document-server.sh` command to `docker-compose.yml` file and add something like 
```
command: >
    bash -c "/var/www/onlyoffice/documentserver/npm/node_modules/.bin/json -f /etc/onlyoffice/documentserver/default.json -I -e 'this.services.CoAuthoring.requestDefaults.rejectUnauthorized=false'
    && bash /app/onlyoffice/run-document-server.sh"
```

I didn't test it through

**Comment by mrwormo** [comment]
@ShockwaveNN Thx for the time spent, but it doesn't work. Dont't bother, i will continue to edit the file after the container has started...

**Comment by ShockwaveNN** [comment]
This issue is closed, seems original problem was resolved via update of nodejs to version 8
If not - I think it's better to create new issue

**Comment by ReinerNippes** [comment]
> This issue is closed, seems original problem was resolved via update of nodejs to version 8
> If not - I think it's better to create new issue

no. it's still not possible to use selfsigned certifcates.
and the workaround to change the file `/etc/onlyoffice/documentserver/default.json` inside the container would not survive an update. or?

**Comment by jcklpe** [comment]
Can confirm that Reiner is correct. This issue wasn't fixed until I used the temporary fix.

**Comment by Legomegger** [comment]
hello, even when I exec the script given by ShockwaveNN, onlyoffice still errors with this message. The value though has been changed, im using docker-compose

**Comment by zner0L** [comment]
There actually is a way to do this properly and without disabling certificate verification. You can add your own CAs (or rather, replace nodejs' CA store) by adding them in the `agentOptions` of `request`, which takes in the options you can define in the [TLS Secure Context](https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options):

```json
"services.CoAuthoring.requestDefaults" {
    "agentOptions": {
        "ca": "<your pem style CA cert>"
    }
}
```

**Comment by nmaludy** [comment]
> @mrwormo I think you can try to move running `run-document-server.sh` command to `docker-compose.yml` file and add something like
> 
> ```
> command: >
>     bash -c "/var/www/onlyoffice/documentserver/npm/node_modules/.bin/json -f /etc/onlyoffice/documentserver/default.json -I -e 'this.services.CoAuthoring.requestDefaults.rejectUnauthorized=false'
>     && bash /app/onlyoffice/run-document-server.sh"
> ```
> 
> I didn't test it through

I got this working using a modified version of this suggestion, basically inserting the edit in the docker run command:

```
docker run -i -t -d -p 8443:443 -v /var/www/onlyoffice/Data:/var/www/onlyoffice/Data  onlyoffice/documentserver bash -c "/var/www/onlyoffice/documentserver/npm/json -f /etc/onlyoffice/documentserver/default.json -I -e 'this.services.CoAuthoring.requestDefaults.rejectUnauthorized=false' && bash /app/onlyoffice/run-document-server.sh"
```

**Comment by lgzcoollg** [comment]
> > @mrwormo I think you can try to move running `run-document-server.sh` command to `docker-compose.yml` file and add something like
> > ```
> > command: >
> >     bash -c "/var/www/onlyoffice/documentserver/npm/node_modules/.bin/json -f /etc/onlyoffice/documentserver/default.json -I -e 'this.services.CoAuthoring.requestDefaults.rejectUnauthorized=false'
> >     && bash /app/onlyoffice/run-document-server.sh"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I didn't test it through
> 
> I got this working using a modified version of this suggestion, basically inserting the edit in the docker run command. Problem in the example above is trying to use `/var/www/onlyoffice/documentserver/npm/node_modules/.bin/json` that doesn't exist. Instead need to use `/var/www/onlyoffice/documentserver/npm/bin/json`:
> 
> ```
> docker run -i -t -d -p 8443:443  -v /var/www/onlyoffice/Data:/var/www/onlyoffice/Data \
>   --entrypoint "/bin/bash" \
>   onlyoffice/documentserver \
>   -c "/var/www/onlyoffice/documentserver/npm/json -f /etc/onlyoffice/documentserver/default.json -I -e 'this.services.CoAuthoring.requestDefaults.rejectUnauthorized=false' && /app/ds/run-document-server.sh"
> ```

Docker tag:6.4,  do not find /var/www/onlyoffice/documentserver/npm/json

**Comment by lgzcoollg** [comment]
> > @mrwormo I think you can try to move running `run-document-server.sh` command to `docker-compose.yml` file and add something like
> > ```
> > command: >
> >     bash -c "/var/www/onlyoffice/documentserver/npm/node_modules/.bin/json -f /etc/onlyoffice/documentserver/default.json -I -e 'this.services.CoAuthoring.requestDefaults.rejectUnauthorized=false'
> >     && bash /app/onlyoffice/run-document-server.sh"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I didn't test it through
> 
> I got this working using a modified version of this suggestion, basically inserting the edit in the docker run command. Problem in the example above is trying to use `/var/www/onlyoffice/documentserver/npm/node_modules/.bin/json` that doesn't exist. Instead need to use `/var/www/onlyoffice/documentserver/npm/bin/json`:
> 
> ```
> docker run -i -t -d -p 8443:443  -v /var/www/onlyoffice/Data:/var/www/onlyoffice/Data \
>   --entrypoint "/bin/bash" \
>   onlyoffice/documentserver \
>   -c "/var/www/onlyoffice/documentserver/npm/json -f /etc/onlyoffice/documentserver/default.json -I -e 'this.services.CoAuthoring.requestDefaults.rejectUnauthorized=false' && /app/ds/run-document-server.sh"
> ```

not work in docker image tags 7.0.0

**Comment by ShockwaveNN** [comment]
You can now use docker env key `USE_UNAUTHORIZED_STORAGE`

**Comment by lgzcoollg** [comment]
> You can now use docker env key `USE_UNAUTHORIZED_STORAGE`

Seccused!
-e USE_UNAUTHORIZED_STORAGE=true

**Comment by mrwormo** [comment]
> You can now use docker env key `USE_UNAUTHORIZED_STORAGE`

Yeah ! It's working with tag:6.4.2.
Not tested with tag:7

**Comment by webagroprom** [comment]
```
 #- LARGER_FILE_LIMITS=true
    ports:
      - '9050:80'
      - '9000:443'
    stdin_open: true
    restart: always
    stop_grace_period: 120s
    command: bash -c "/var/www/onlyoffice/documentserver/npm/json -f /etc/onlyoffice/documentserver/default.json -I -e 'this.services.CoAuthoring.requestDefaults.rejectUnauthorized=false' && bash /app/onlyoffice/run-document-server.sh"
    volumes:
```

Added to configuration docker-compose.yml launched container docker-compose up -d

nextcloud: **Error while downloading the document file to be converted.) (версия 7.1.0.215)**

What am I doing wrong ? How to solve this error?

**Comment by webagroprom** [comment]
> > > @mrwormo I think you can try to move running `run-document-server.sh` command to `docker-compose.yml` file and add something like
> > > ```
> > > command: >
> > >     bash -c "/var/www/onlyoffice/documentserver/npm/node_modules/.bin/json -f /etc/onlyoffice/documentserver/default.json -I -e 'this.services.CoAuthoring.requestDefaults.rejectUnauthorized=false'
> > >     && bash /app/onlyoffice/run-document-server.sh"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I didn't test it through
> > 
> > 
> > I got this working using a modified version of this suggestion, basically inserting the edit in the docker run command. Problem in the example above is trying to use `/var/www/onlyoffice/documentserver/npm/node_modules/.bin/json` that doesn't exist. Instead need to use `/var/www/onlyoffice/documentserver/npm/bin/json`:
> > ```
> > docker run -i -t -d -p 8443:443  -v /var/www/onlyoffice/Data:/var/www/onlyoffice/Data \
> >   --entrypoint "/bin/bash" \
> >   onlyoffice/documentserver \
> >   -c "/var/www/onlyoffice/documentserver/npm/json -f /etc/onlyoffice/documentserver/default.json -I -e 'this.services.CoAuthoring.requestDefaults.rejectUnauthorized=false' && /app/ds/run-document-server.sh"
> > ```
> 
> Docker tag:6.4, input command after docker run.and it work

**Can you show an example of how to correctly add (as you added) data to the docker-compose.yml configuration file ?**

**Comment by ShockwaveNN** [comment]
@webagroprom I think for you it's better to create new discusttion\new issue since your problem doesn't seem any relation to original issue with certificate verification

**Comment by rasmu31** [comment]
Hello,

To resolve the same problem with LEt's encrypt cert, I didn't modify onlyoffice configuration file default.json.
I only change ssl_certificate in nginx configuration concerning onlyoffice server block :
ssl_certificate /etc/ssl/certs/fullchain.pem;
ssl_certificate_key /etc/ssl/private/privkey.pem;

I used fullchain.pem instead of cert.pem and problem was solved.

**Comment by douglascrp** [comment]
> > You can now use docker env key `USE_UNAUTHORIZED_STORAGE`
> 
> Seccused! -e USE_UNAUTHORIZED_STORAGE=true

Yes, it works

**Comment by mirrornight** [comment]
> You can now use docker env key `USE_UNAUTHORIZED_STORAGE`

not work in docker image tags onlyoffice/documentserver-de:7.3.3.50.

**Comment by luisnabais** [comment]
USE_UNAUTHORIZED_STORAGE doesn't work with me either, in onlyoffice/documentserver:8.3.1.1.
I'm not using self-signed certificates, I'm using valid LE certificates (fullchain/key pair), which resolve successfully using curl in internal network and inside containers, without using -k flag).
Changing rejectUnauthorized to false in defaults.json works, but as it's not a fixed solution (when I upgrade container it's lost), I believe the option USE_UNAUTHORIZED_STORAGE is somehow broken.
